### ISSUE TITLE
Wrong number of digits after the decimal point

### ISSUE THREAD

**Issue by jansivans** [super-ienien/percent-round#3]
Hi.
With such input:
```
percentRound([1, 1, 1], 2);
```
Result is:
```
[
    33.340000000001936,
    33.33000000000194,
    33.33000000000194
]
```
I was expecting to have just 2 numbers after the decimal point here.

**Comment by super-ienien** [comment]
Hi,

Thanks for reporting this. It is due to how javascript handles floating points : [some explanation here](https://www.w3schools.com/js/js_numbers.asp#:~:text=JavaScript%20Numbers%20are%20Always%2064%2Dbit%20Floating%20Point&text=JavaScript%20numbers%20are%20always%20stored,the%20international%20IEEE%20754%20standard.)

in javascript : `var x = 0.2 + 0.1;         // x will be 0.30000000000000004`

I will look into a fix for this. In the mean time as a workaround you can do this : 

`percentRound([1, 1, 1], 2).map(result => parseFloat(result.toFixed(2)));`

**Comment by super-ienien** [comment]
I fixed this by treating the decimal numbers as integers and convert them back to floats after all the computation are done
